<a href="https://colab.research.google.com/github/Rnhondova/attention-learn-to-route/blob/master/Attention.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [74]:
# This ensures that a gpu is being used by the current google colab session.

gpu_info = !nvidia-smi
gpu_info = '\n'.join(gpu_info)
if gpu_info.find('failed') >= 0:
  print('Select the Runtime > "Change runtime type" menu to enable a GPU accelerator, ')
  print('and then re-execute this cell.')
else:
  print(gpu_info)

Sun Mar 28 23:40:34 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.56       Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   34C    P0    26W / 250W |      0MiB / 16280MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
# This code block is used to access your google drive

from google.colab import drive
ROOT = "/content/drive"
drive.mount(ROOT)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [2]:
!git clone https://github.com/Rnhondova/garage.git

Cloning into 'garage'...
remote: Enumerating objects: 16, done.
remote: Counting objects: 100% (16/16), done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 25274 (delta 4), reused 13 (delta 2), pack-reused 25258
Receiving objects: 100% (25274/25274), 58.59 MiB | 22.94 MiB/s, done.
Resolving deltas: 100% (18787/18787), done.


In [22]:
%cd garage/

[Errno 2] No such file or directory: 'garage/'
/content/garage/src/attention-learn-to-route


In [4]:
!git submodule update --init --recursive

Submodule 'src/attention-learn-to-route' (https://github.com/Rnhondova/attention-learn-to-route.git) registered for path 'src/attention-learn-to-route'
Cloning into '/content/garage/src/attention-learn-to-route'...
Submodule path 'src/attention-learn-to-route': checked out 'f2c124704cd2cdcbcef3a8997982985ee0b0d068'


In [5]:
#%cd garage/src/garage/torch/algos/attention-learn-to-route/
%cd src/attention-learn-to-route/

/content/garage/src/attention-learn-to-route


In [49]:
!ls

 attention_gym.py	   nets			    run.py
 Attention.ipynb	   options.py		    simple_tsp.ipynb
 environment.yml	   outputs		   'train copy.py'
 eval.py		   plot_vrp.ipynb	    train_copy.py
 garage_requirements.txt   pretrained		    train.py
 generate_data.py	   problems		    TRPO_Attention.py
 images			   __pycache__		    utils
 LICENSE		   README.md
 logs			   reinforce_baselines.py


In [7]:
!pip install --upgrade pip
!pip install -r garage_requirements.txt

     |████████████████████████████████| 1.5MB 5.6MB/s 
  Found existing installation: pip 19.3.1
    Uninstalling pip-19.3.1:
      Successfully uninstalled pip-19.3.1
     |████████████████████████████████| 239 kB 5.9 MB/s 
     |████████████████████████████████| 47.5 MB 79 kB/s 
     |████████████████████████████████| 2.0 MB 90.5 MB/s 
     |████████████████████████████████| 308 kB 90.9 MB/s 
     |████████████████████████████████| 1.3 MB 64.4 MB/s 
     |████████████████████████████████| 201 kB 75.7 MB/s 
     |████████████████████████████████| 3.1 MB 65.1 MB/s 
     |████████████████████████████████| 72 kB 633 kB/s 
     |████████████████████████████████| 65 kB 4.0 MB/s 
     |████████████████████████████████| 78 kB 7.7 MB/s 
     |████████████████████████████████| 127 kB 74.0 MB/s 
     |████████████████████████████████| 159 kB 86.4 MB/s 
     |████████████████████████████████| 97 kB 8.2 MB/s 
     |████████████████████████████████| 131 kB 88.9 MB/s 
     |████████████████████████

In [73]:
!python run.py --graph_size 20 --batch_size 512 --problem cvrp --baseline rollout --run_name 'vrp100_rollout' --epoch_size 12800 --n_epochs 1

2021-03-28 22:18:56.295005: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
{'baseline': 'rollout',
 'batch_size': 512,
 'bl_alpha': 0.05,
 'bl_warmup_epochs': 1,
 'checkpoint_encoder': False,
 'checkpoint_epochs': 1,
 'data_distribution': None,
 'embedding_dim': 128,
 'epoch_size': 12800,
 'epoch_start': 0,
 'eval_batch_size': 1024,
 'eval_only': False,
 'exp_beta': 0.8,
 'graph_size': 20,
 'hidden_dim': 128,
 'load_path': None,
 'log_dir': 'logs',
 'log_step': 50,
 'lr_critic': 0.0001,
 'lr_decay': 1.0,
 'lr_model': 0.0001,
 'max_grad_norm': 1.0,
 'model': 'attention',
 'n_encode_layers': 3,
 'n_epochs': 1,
 'no_cuda': False,
 'no_progress_bar': False,
 'no_tensorboard': False,
 'normalization': 'batch',
 'output_dir': 'outputs',
 'problem': 'cvrp',
 'resume': None,
 'run_name': 'vrp100_rollout_20210328T221858',
 'save_dir': 'outputs/cvrp_20/vrp100_rollout_20210328T221858',
 'seed': 1234,
 'shrink_size': None,
 'ta

In [ ]:
# Make sure this points to the project folder

%cd drive/'My Drive'/CORL

/content/drive/My Drive/CORL


In [ ]:
%cd attention

/content/drive/My Drive/CORL/attention


In [ ]:
import wandb

wandb.login()

<IPython.core.display.Javascript object>

wandb: You can find your API key in your browser here: https://wandb.ai/authorize


wandb: Paste an API key from your profile and hit enter: ··········


wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc


True

In [ ]:
# This block will run the originial attention code with the below settings
# The save_hrs are the checkpoint hours to save the model

!python run.py --graph_size 100 --batch_size 64 --problem cvrp --baseline rollout --run_name 'vrp100_rollout' --save_hrs 5 10 --epoch_size 12800 --n_epochs 500

# this is an example of how to run evolution code
#!python vrp_evolve.py --save_dir ../models/att_evo --save_hrs 2 3 4 5 6 8 10 --sigma 0.001 --lr 0.000001 --dataset_size 12800 --epochs 500

2021-01-26 13:50:45.455415: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
wandb: Currently logged in as: rnhondova (use `wandb login --relogin` to force relogin)
2021-01-26 13:50:59.439484: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
wandb: Tracking run with wandb version 0.10.15
wandb: Syncing run eternal-haze-2
wandb: ⭐️ View project at https://wandb.ai/rnhondova/pytorch-attention-model
wandb: 🚀 View run at https://wandb.ai/rnhondova/pytorch-attention-model/runs/25jujl2f
wandb: Run data is saved locally in /content/drive/My Drive/CORL/attention/wandb/run-20210126_135052-25jujl2f
wandb: Run `wandb offline` to turn off syncing.

{'baseline': 'rollout',
 'batch_size': 64,
 'bl_alpha': 0.05,
 'bl_warmup_epochs': 1,
 'checkpoint_encoder': False,
 'checkpoint_epochs': 1,
 'data_distribution': None,
 'embedding_dim': 128,
 'epoch_size': 12800,
 'e

In [23]:
!git status

HEAD detached at b1b1b0c
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   run.py
	deleted:    train copy.py

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	Makefile
	garage_requirements.txt
	train_copy.py

no changes added to commit (use "git add" and/or "git commit -a")


In [24]:
!git add -A

In [27]:
!git config --global user.email "rnhondova@yahoo.com"

In [28]:
!git config --global user.name "Ronald Nhondova"

In [29]:
!git commit -m "Add required files to set garage"

[detached HEAD 18b3b07] Add required files to set garage
 4 files changed, 53 insertions(+), 16 deletions(-)
 create mode 100644 Makefile
 create mode 100644 garage_requirements.txt
 rename train copy.py => train_copy.py (87%)


In [31]:
!git push origin HEAD:master

fatal: could not read Username for 'https://github.com': No such device or address


In [43]:
import numpy as np
test_ = np.array([1,2,3,4,5,6])
test_ = test_.reshape(test_.shape[0],1)
for reward in test_:
  print(reward[::-1])

[1]
[2]
[3]
[4]
[5]
[6]


In [59]:
import scipy.signal
def discount_cumsum(x, discount):
    """Discounted cumulative sum.

    See https://docs.scipy.org/doc/scipy/reference/tutorial/signal.html#difference-equation-filtering  # noqa: E501
    Here, we have y[t] - discount*y[t+1] = x[t]
    or rev(y)[t] - discount*rev(y)[t-1] = rev(x)[t]

    Args:
        x (np.ndarrary): Input.
        discount (float): Discount factor.

    Returns:
        np.ndarrary: Discounted cumulative sum.


    """
    return scipy.signal.lfilter([1], [1, float(-discount)], x[::-1],
                                axis=-1)[::-1]
                  
def pad_tensor(x, max_len, mode='zero'):
    """Pad tensors.

    Args:
        x (numpy.ndarray): Tensors to be padded.
        max_len (int): Maximum length.
        mode (str): If 'last', pad with the last element, otherwise pad with 0.

    Returns:
        numpy.ndarray: Padded tensor.

    """
    padding = np.zeros_like(x[0])
    if mode == 'last':
        padding = x[-1]

    return np.concatenate(
        [x, np.tile(padding, (max_len - len(x), ) + (1, ) * np.ndim(x[0]))])

In [42]:
for reward in test_:
  (reward[::-1])

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [56]:
import torch
rewards = torch.Tensor(test_)
returns = torch.Tensor(
    np.stack([
        discount_cumsum(reward, 0.5)
        for reward in test_
    ]))

In [57]:
returns

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.]])

In [63]:
pad_tensor(test_, len(test_), mode='last')

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])